// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:d66bb6b7-4086-49f0-af19-dab9e624f6a9",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_RMt1KusHA",
    "aws_user_pools_web_client_id": "28l1tv1iq0j1tf3hv3ijp5sdk3",
    "oauth": {},
    "aws_user_files_s3_bucket": "amplifybucketamir45939-vscode",
    "aws_user_files_s3_bucket_region": "eu-west-1"
};


export default awsmobile;
